# Generated by Django 4.2.9 on 2024-02-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sssa_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeFieldData',
            fields=[
                ('nid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('vid', models.PositiveIntegerField()),
                ('type', models.CharField(db_collation='ascii_general_ci', db_comment='The ID of the target entity.', max_length=32)),
                ('langcode', models.CharField(db_collation='ascii_general_ci', max_length=12)),
                ('status', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('uid', models.PositiveIntegerField(db_comment='The ID of the target entity.')),
                ('created', models.IntegerField()),
                ('changed', models.IntegerField()),
                ('promote', models.IntegerField()),
                ('sticky', models.IntegerField()),
                ('default_langcode', models.IntegerField()),
                ('revision_translation_affected', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'node_field_data',
                'db_table_comment': 'The data table for node entities.',
                'managed': False,
            },
        ),
    ]
