# Generated by Django 4.2.9 on 2024-02-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sssa_app', '0002_nodefielddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeFieldTypes',
            fields=[
                ('bundle', models.CharField(db_collation='ascii_general_ci', db_comment='The field instance bundle to which this row belongs, used when deleting a field instance', max_length=128)),
                ('deleted', models.IntegerField(db_comment='A boolean indicating whether this data item has been deleted')),
                ('entity_id', models.PositiveIntegerField(db_comment='The entity id this data is attached to', primary_key=True, serialize=False)),
                ('revision_id', models.PositiveIntegerField(db_comment='The entity revision id this data is attached to')),
                ('langcode', models.CharField(db_collation='ascii_general_ci', db_comment='The language code for this data item.', max_length=32)),
                ('delta', models.PositiveIntegerField(db_comment='The sequence number for this data item, used for multi-value fields')),
                ('field_types_target_id', models.PositiveIntegerField(db_comment='The ID of the target entity.')),
            ],
            options={
                'db_table': 'node__field_types',
                'db_table_comment': 'Data storage for node field field_types.',
                'managed': False,
            },
        ),
    ]
