# Generated by Django 4.2.9 on 2024-02-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeBody',
            fields=[
                ('bundle', models.CharField(db_collation='ascii_general_ci', db_comment='The field instance bundle to which this row belongs, used when deleting a field instance', max_length=128)),
                ('deleted', models.IntegerField(db_comment='A boolean indicating whether this data item has been deleted')),
                ('entity_id', models.PositiveIntegerField(db_comment='The entity id this data is attached to', primary_key=True, serialize=False)),
                ('revision_id', models.PositiveIntegerField(db_comment='The entity revision id this data is attached to')),
                ('langcode', models.CharField(db_collation='ascii_general_ci', db_comment='The language code for this data item.', max_length=32)),
                ('delta', models.PositiveIntegerField(db_comment='The sequence number for this data item, used for multi-value fields')),
                ('body_value', models.TextField()),
                ('body_summary', models.TextField(blank=True, null=True)),
                ('body_format', models.CharField(blank=True, db_collation='ascii_general_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'node__body',
                'db_table_comment': 'Data storage for node field body.',
                'managed': False,
            },
        ),
    ]
