# Generated by Django 4.2.9 on 2024-02-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NodeBody',
        ),
    ]
