# Generated by Django 4.2.9 on 2024-02-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sssa_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Alst',
        ),
    ]
