# Generated by Django 4.2.9 on 2024-02-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sssa_app', '0002_rename_book_alst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alst',
            name='name',
        ),
        migrations.AddField(
            model_name='alst',
            name='catalogue_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='catalogue_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='comments',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='data_last_amended',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='data_record_input',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='date',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='disc_matrix_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='fieldworker',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='informant_artist',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='native_area_county',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='old_number_rl',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='place_recorded',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='reference',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='summary',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='tale_reference',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='type_of_material',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
