# Generated by Django 4.2.9 on 2024-04-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sssa_app', '0003_remove_alst_name_alst_catalogue_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alst',
            name='camera_operator',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='first_line',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='instrument',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='parent',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alst',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
