# Generated by Django 4.2.9 on 2024-04-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sssa_app', '0004_alst_camera_operator_alst_first_line_alst_instrument_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alst',
            options={'managed': False},
        ),
    ]
