# Generated by Django 4.2.9 on 2024-07-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sssa_app', '0005_alter_alst_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alst',
            table='sssa_jason_db',
        ),
    ]
