# Generated by Django 4.2.9 on 2024-07-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sssa_app', '0006_alter_alst_table'),
    ]

    operations = [
    ]
