# Generated by Django 4.2.9 on 2025-01-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sssa_app', '0007_auto_20240704_1323'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alst',
            table='sssa_app_alst',
        ),
    ]
