# Generated by Django 4.2.9 on 2025-01-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sssa_app', '0008_alter_alst_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alst',
            table='alst_and_mndx_csv_3',
        ),
    ]
