# Generated by Django 4.2.9 on 2025-01-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sssa_app', '0009_alter_alst_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alst',
            table='last_csv_file',
        ),
    ]
